### ISSUE TITLE
Doesn't work for Sublime Text 3

### ISSUE THREAD

**Issue by sheerun** [noklesta/SublimeRailsNav#7]
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "X/importlib/__init__.py", line 88, in import_module
  File "<frozen importlib._bootstrap>", line 1577, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1525, in _find_and_load_unlocked
  File "/Users/sheerun/Library/Application Support/Sublime Text 3/Installed Packages/Simple Rails Navigator.sublime-package/SublimeRailsNav.py", line 5, in <module>
ImportError: No module named 'recursive_glob'
```

**Comment by noklesta** [comment]
Are you using the ST3 branch? See the README for instructions on how to do that. The master branch is not compatible with Sublime Text 3.

**Comment by sheerun** [comment]
Oh, sorry :(

**Comment by sheerun** [comment]
The package manager for sublime need to introduce spliting packages on working with st2 and st3..
